name: Cypress

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          DEBUG: '@cypress/github-action'
        with:
          config-file: cypress-mocha.json

      - run: ls -la
      - run: ls -la cypress
      - run: ls -la cypress/results

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Cypress Tests
          path: cypress/results/results.json
          reporter: mocha-json
          fail-on-error: true